x = np.linspace(0, 1, 100)
print("### integrate ###")
%timeit integrate(x, 10 * x + 2)
print("### generate_graph ###")
%timeit generate_graph([1., 2., -2.], show_figure=False)
print("### generate_sinus ###")
%timeit generate_sinus(show_figure=False)
print("### download_data ###")
%timeit download_data()
print("### get_avg_temp ###")
%timeit get_avg_temp(download_data())